services:
  api:
    image: galapagos-api
    container_name: galapagos-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - '8000:8000'
    depends_on:
      - mongodb
      - neo4j
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://galapagos-mongodb:27017
      - NEO4J_URI=bolt://galapagos-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=galapagos2024

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: galapagos-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=galapagos

  neo4j:
    image: neo4j:5.12.0
    container_name: galapagos-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/galapagos2024
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]

  frontend:
    build: ./frontend
    container_name: galapagos-frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8000/graphql
    volumes:
      - ./frontend:/app
    depends_on:
      - api    

volumes:
  mongo-data:
  neo4j-data:
  neo4j-logs:
